// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Blurs the given region behind the Flutter window. With no rectangles the
/// whole window is blurred, following it across resizes.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<BackgroundBlurLinuxRect>, ffi.Size)
>()
external ffi.Pointer<ffi.Char> background_blur_linux_enable(
  ffi.Pointer<BackgroundBlurLinuxRect> rects,
  int n_rects,
);

/// Removes the blur.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> background_blur_linux_disable();

/// A rectangle in surface-local logical pixels.
final class BackgroundBlurLinuxRect extends ffi.Struct {
  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;
}
