// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Associates the Flutter window with the DBusMenu exported at `service_name`
/// and `object_path` through KWin's AppMenu protocol.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> linux_app_menu_set_address(
  ffi.Pointer<ffi.Char> service_name,
  ffi.Pointer<ffi.Char> object_path,
);

/// Removes the window's menu association.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> linux_app_menu_clear();
