// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Asks KWin to paint the Flutter window's decoration with the KDE color scheme
/// at `path`. An unmapped window gets the scheme once it is mapped.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> kde_color_scheme_set_palette(
  ffi.Pointer<ffi.Char> path,
);

/// Returns the decoration to the system color scheme.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> kde_color_scheme_reset_palette();
