name: background_blur_linux
description: "Enables the KWin compositor background blur effect for Flutter windows on Linux (Wayland)."
version: 0.0.3
homepage:

resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: '>=3.3.0'

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.4

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
